# Generated by Django 3.0.7 on 2020-07-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.IntegerField()),
                ('fee', models.FloatField()),
                ('subject', models.ManyToManyField(to='app.CourseModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.IntegerField()),
                ('salary', models.FloatField()),
                ('subject', models.ManyToManyField(to='app.CourseModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
